CONFIG = {
    # facebook token the voice kid
    'FACEBOOK_TOKEN_GHVN': 'EAAcHG1IN8z4BAK0pZB2bwSEYRZANCehWvWjTuZCGIZAYzMWaPZCuiLiZBdYo9SwGoUfY9yzbRQZBZCq4E7pNMGc4Dg31kVf730ZAotBbi3M8iG42bdQnpGkzYWzfDRmSj0wfYKZCqapZCcz3ZBPLdMVJFLkNZBZAnjZCBzJHGS0WK4ZAJqWQ8ZBCJZCsWmAJ7m',
    'FACEBOOK_TOKEN_CDHH': 'EAAFTMCSH9fYBABZAd5wgNypgC4mZAZAkMfxHfptY4eW7zDZBSPMqFOYxEQo8jU6nPxWmZB9iQmDZCkmmZC45TsmjUuQRyYEoPqXbcyh2pkUeox4gkRfH6aoFAAoZCEiZAdRZA4YdZCnLkcJjlT0Dw8DnklS2WZAEmuEGMcs1usNG6GTFP0OJeGbECaoz',
    # facebook token Cb_py
    # 'FACEBOOK_TOKEN': 'EAAHIaKy7WHIBAKygq64AbmRmFp47wyWM0tE2NjNLilolZAPsvGc12PG3iVQjwOhXJwJTbxq6oU5sEtfHmWrKnxlkL2vMsoLHWZB7AsyveXnDZBdzdYRRLv2hu2Q0QVDVISKKb9dBAb8RyCjOqwELXhJf9QkqlRmynlA66ZCmjruCAaHYbQz6',
    'VERIFY_TOKEN': 'phuc123',
    'SERVER_URL': 'https://yourdomain'
}
